<!DOCTYPE html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Saving Sight - Demo Project</title>
    <link rel="stylesheet" href="/css/bootstrap-fileupload.min.css" type="text/css"/>
    <link rel="stylesheet" href="/css/bootstrap-timepicker.min.css" type="text/css"/>
    <?php echo $this->headTitle($this->translate('Saving Sight - Demo Project'))->setSeparator(' - ')->setAutoEscape(FALSE) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?php
    echo $this->headLink(array(
        'rel'  => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
    <?php
    echo $this->headScript()->offsetSetFile(10, $this->basePath() . '/js/jquery-1.7.min.js')
        ->offsetSetFile(20, $this->basePath() . '/js/jquery-ui-1.9.1.min.js')
        ->offsetSetFile(30, $this->basePath() . '/js/custom.js');
    ?>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Saving Sight - Demo Project') ?>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="<?php echo $this->url('home') ?>" title="Home">Home</a></li>
                <?php if ($this->user()->role != 'guest'): ?>
                    <li><a href="<?php echo $this->url('user', array('action' => 'update', 'id' => $this->user()->id)) ?>" title="All Events">Profile</a></li>
                <?php endif; ?>
                <?php if ($this->user()->role == 'guest'): ?>
                    <li>
                        <a href="<?php echo $this->url('user', array('action' => 'register')) ?>" title="News">Register</a>
                    </li>
                    <li><a href="<?php echo $this->url('auth') ?>" title="News">Login</a></li>
                <?php else : ?>
                    <li>
                        <a href="<?php echo $this->url('auth', array('action' => 'logout')) ?>" title="News">Logout</a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>
<div class="main-container">
    <div id="layout">
        <div class="container">
            <div id="header">
                <?php
                $t = time();
                $z = date("Z", $t);
                $offset = $this->user()->timezone_offset;
                ?>
                <b>Welcome! </b><?php echo $this->user()->first_name . ' ' . $this->user()->last_name ?><br>

                <?php if ($this->user()->role != 'guest'): ?>
                    <b>Email: </b><?php echo $this->user()->email ?><br>
                    <b>Current Time: </b><?php echo date("h:i A", $t - $offset - $z + 3600); ?><br>
                <?php endif; ?>
            </div>

            <div id="content">
                <?php echo $this->content; ?>
            </div>

            <div class="clr"></div>
        </div>
    </div>
</div>
</body></html>